# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlotAllocation
                                 A QGIS plugin
 Plot alocation for forest inventory
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-28
        copyright            : (C) 2024 by Vinicius Richter
        email                : vinicius00rich@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlotAllocation class from file PlotAllocation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .plot_allocation import PlotAllocation
    return PlotAllocation(iface)
    self.add_action(
        "new_icon.png",  # Update with the correct icon file name
        text=self.tr(u'Plot Allocation FPTools'),
        callback=self.run,
        parent=self.iface.mainWindow()
    )
